package form;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.dbKoneksi;
import model.bulanEntity;
import model.jumlahEntity;

/**
 *
 * @author asus
 */
public class inFrame_Jumlah extends javax.swing.JInternalFrame {

    private ResultSet rs;
    private Statement st;
    private PreparedStatement pst;
    private Connection conn;

    jumlahEntity jumlah;
    bulanEntity bulan;

    public inFrame_Jumlah() {
        initComponents();

        tableAbsensi();

        // setNomor bulan ke jComboBox
        dbKoneksi.bindKd_Bulan(cbxKode_bulan);

        // bind Nip from tbPegawai
        dbKoneksi.bindNIP_toAbsensi(cbxNip_jml);
        
        
        lbNom.disable();
        lnNo_Urut.disable();
    }

    public void setInput_Num(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxNip_jml = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spHadir = new javax.swing.JSpinner();
        spSakit = new javax.swing.JSpinner();
        spIzin = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spAlpa = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        spCuti = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spLembur = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spTugas = new javax.swing.JSpinner();
        txNmBulan_jml = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txTahun_jml = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txKet_jml = new javax.swing.JTextField();
        cbxKode_bulan = new javax.swing.JComboBox();
        lbNom = new javax.swing.JLabel();
        lnNo_Urut = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbJumlah = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        txCari_jml = new javax.swing.JTextField();
        btCari_jml = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btSimpan_jml = new javax.swing.JButton();
        btUbah_jml = new javax.swing.JButton();
        btBatal_jml = new javax.swing.JButton();
        btHapus_jml = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Jumlah Absensi");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Add_User_Male_20px.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nip Pegawai");

        cbxNip_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxNip_jml.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Kode Bulan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jumlah Hadir");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah Sakit");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jumlah Izin");

        spHadir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spHadir.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spSakit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spSakit.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spIzin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spIzin.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Jumlah Tanpa Keterangan");

        spAlpa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spAlpa.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Jumlah Cuti");

        spCuti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spCuti.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Jumlah Lembur");

        spLembur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spLembur.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Jumlah Tugas Luar");

        spTugas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spTugas.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        txNmBulan_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Nama Bulan");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Tahun");

        txTahun_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txTahun_jml.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txTahun_jml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txTahun_jmlKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Jumlah sebulan");

        txKet_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txKet_jml.setForeground(new java.awt.Color(255, 255, 0));
        txKet_jml.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txKet_jml.setToolTipText("Total nilai akan muncul secara otomatis ketika data telah ditambah");
        txKet_jml.setEnabled(false);

        cbxKode_bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        cbxKode_bulan.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbxKode_bulanPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lbNom.setText("No");
        lbNom.setToolTipText("No ini hanya sebagai penentu untuk melakukan penghapusan atau pembaharuan data");

        lnNo_Urut.setToolTipText("No ini hanya sebagai penentu untuk melakukan penghapusan atau pembaharuan data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txTahun_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spIzin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spSakit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spAlpa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spCuti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txKet_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txNmBulan_jml)
                            .addComponent(cbxNip_jml, 0, 167, Short.MAX_VALUE)
                            .addComponent(cbxKode_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnNo_Urut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNom, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lnNo_Urut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxNip_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(cbxKode_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNmBulan_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTahun_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spSakit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spIzin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spAlpa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spCuti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txKet_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbJumlah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbJumlah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbJumlah.setToolTipText("Data pada tabel dapat dipilih setelah dlakukan pencarian");
        tbJumlah.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbJumlah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbJumlah.setDropMode(javax.swing.DropMode.INSERT);
        tbJumlah.setEnabled(false);
        tbJumlah.setSelectionForeground(new java.awt.Color(51, 255, 0));
        tbJumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJumlahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbJumlah);

        txCari_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txCari_jml.setToolTipText("Masukan nip pegawai");
        txCari_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCari_jmlActionPerformed(evt);
            }
        });
        txCari_jml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCari_jmlKeyTyped(evt);
            }
        });

        btCari_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCari_jml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Search_20px.png"))); // NOI18N
        btCari_jml.setText("Cari...");
        btCari_jml.setToolTipText("Cari data jumlah berdasarkan nip");
        btCari_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCari_jmlActionPerformed(evt);
            }
        });

        btSimpan_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSimpan_jml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Save_as_20px.png"))); // NOI18N
        btSimpan_jml.setText("Simpan");
        btSimpan_jml.setToolTipText("Simpan data jumlah baru ke penyimpanan");
        btSimpan_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpan_jmlActionPerformed(evt);
            }
        });

        btUbah_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btUbah_jml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Update_20px.png"))); // NOI18N
        btUbah_jml.setText("Ubah");
        btUbah_jml.setToolTipText("Simpan hasil perubahan");
        btUbah_jml.setEnabled(false);
        btUbah_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbah_jmlActionPerformed(evt);
            }
        });

        btBatal_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btBatal_jml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Delete_20px.png"))); // NOI18N
        btBatal_jml.setText("Batal");
        btBatal_jml.setToolTipText("Batalkan perubahan atau penambahan data");
        btBatal_jml.setEnabled(false);
        btBatal_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatal_jmlActionPerformed(evt);
            }
        });

        btHapus_jml.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btHapus_jml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Trash_Can_20px.png"))); // NOI18N
        btHapus_jml.setText("Hapus");
        btHapus_jml.setToolTipText("Hapus data yang telah dipilih dari penyimpanan");
        btHapus_jml.setEnabled(false);
        btHapus_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapus_jmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btCari_jml)
                                .addGap(18, 18, 18)
                                .addComponent(txCari_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btSimpan_jml)
                                .addGap(18, 18, 18)
                                .addComponent(btUbah_jml)
                                .addGap(18, 18, 18)
                                .addComponent(btHapus_jml)
                                .addGap(18, 18, 18)
                                .addComponent(btBatal_jml)
                                .addGap(84, 84, 84)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCari_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCari_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUbah_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHapus_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBatal_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpan_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpan_jmlActionPerformed
        tambahJumlah();
        //tambahBulan();
        tableAbsensi();
        clearForm();
    }//GEN-LAST:event_btSimpan_jmlActionPerformed

    private void btBatal_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatal_jmlActionPerformed
        clearForm();
        tableAbsensi();
        btSimpan_jml.setEnabled(true);
        btUbah_jml.setEnabled(false);
        btHapus_jml.setEnabled(false);
        btBatal_jml.setEnabled(false);
        tbJumlah.setEnabled(false);
        
        lbNom.hide();
        lnNo_Urut.hide();
    }//GEN-LAST:event_btBatal_jmlActionPerformed

    private void btUbah_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbah_jmlActionPerformed
        ubahJumlah();
        //ubahBulan();
        tableAbsensi();
        clearForm();

        btSimpan_jml.setEnabled(true);
        btUbah_jml.setEnabled(false);
        btHapus_jml.setEnabled(false);
        btBatal_jml.setEnabled(false);
        tbJumlah.setEnabled(false);
    }//GEN-LAST:event_btUbah_jmlActionPerformed

    private void btHapus_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapus_jmlActionPerformed
        hapusJumlah();
        //hapusBulan();
        tableAbsensi();
        clearForm();

        btSimpan_jml.setEnabled(true);
        btUbah_jml.setEnabled(false);
        btHapus_jml.setEnabled(false);
        btBatal_jml.setEnabled(false);
        tbJumlah.setEnabled(false);
    }//GEN-LAST:event_btHapus_jmlActionPerformed

    private void tbJumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJumlahMouseClicked
        int row = tbJumlah.getSelectedRow();
        TableModel model = tbJumlah.getModel();
        
        try {
            lnNo_Urut.setText(model.getValueAt(row, 0).toString());
            cbxNip_jml.setSelectedItem(model.getValueAt(row, 1).toString());
            cbxKode_bulan.setSelectedItem(model.getValueAt(row, 2));
            txNmBulan_jml.setText(model.getValueAt(row, 3).toString());
            txTahun_jml.setText(model.getValueAt(row, 4).toString());
            String hdr = model.getValueAt(row, 5).toString();
            spHadir.setValue(Integer.valueOf(hdr));
            String skt = model.getValueAt(row, 6).toString();
            spSakit.setValue(Integer.valueOf(skt));
            String izn = model.getValueAt(row, 7).toString();
            spIzin.setValue(Integer.valueOf(izn));
            String alp = model.getValueAt(row, 8).toString();
            spAlpa.setValue(Integer.valueOf(alp));
            String ct = model.getValueAt(row, 9).toString();
            spCuti.setValue(Integer.valueOf(ct));
            String lbr = model.getValueAt(row, 10).toString();
            spLembur.setValue(Integer.valueOf(lbr));
            String tgs = model.getValueAt(row, 11).toString();
            spTugas.setValue(Integer.valueOf(tgs));
            txKet_jml.setText(model.getValueAt(row, 12).toString());

            btSimpan_jml.setEnabled(false);
            btUbah_jml.setEnabled(true);
            btHapus_jml.setEnabled(true);
            btBatal_jml.setEnabled(true);
        } catch (Exception ex) {
            ex.getStackTrace();
        }
    }//GEN-LAST:event_tbJumlahMouseClicked

    private void txTahun_jmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTahun_jmlKeyTyped
        // DISINI HANYA MENERIMA ANGKA
        setInput_Num(evt);
    }//GEN-LAST:event_txTahun_jmlKeyTyped

    private void btCari_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCari_jmlActionPerformed
        cariDataJumlah();
        
    }//GEN-LAST:event_btCari_jmlActionPerformed

    private void txCari_jmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCari_jmlKeyTyped
        setInput_Num(evt);
    }//GEN-LAST:event_txCari_jmlKeyTyped

    private void cbxKode_bulanPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbxKode_bulanPopupMenuWillBecomeInvisible
        LocalDate date = LocalDate.now();
        int year = date.getYear();
        String thn = String.valueOf(year);
        txTahun_jml.setText(thn);
        dbKoneksi.bindNm_BulantoJumlah(cbxKode_bulan, txNmBulan_jml);
    }//GEN-LAST:event_cbxKode_bulanPopupMenuWillBecomeInvisible

    private void txCari_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCari_jmlActionPerformed
        cariDataJumlah();
    }//GEN-LAST:event_txCari_jmlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal_jml;
    private javax.swing.JButton btCari_jml;
    private javax.swing.JButton btHapus_jml;
    private javax.swing.JButton btSimpan_jml;
    private javax.swing.JButton btUbah_jml;
    private javax.swing.JComboBox cbxKode_bulan;
    private javax.swing.JComboBox cbxNip_jml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lnNo_Urut;
    private javax.swing.JSpinner spAlpa;
    private javax.swing.JSpinner spCuti;
    private javax.swing.JSpinner spHadir;
    private javax.swing.JSpinner spIzin;
    private javax.swing.JSpinner spLembur;
    private javax.swing.JSpinner spSakit;
    private javax.swing.JSpinner spTugas;
    private javax.swing.JTable tbJumlah;
    private javax.swing.JTextField txCari_jml;
    private javax.swing.JTextField txKet_jml;
    private javax.swing.JTextField txNmBulan_jml;
    private javax.swing.JTextField txTahun_jml;
    // End of variables declaration//GEN-END:variables

    public Connection konek() throws SQLException, ClassNotFoundException {
        try {
            //
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbAbsensi", "root", "root");
            st = conn.createStatement();
            pst = conn.prepareStatement("SET FOREIGN_KEY_CHECKs=0");
            pst.executeQuery();

            return conn;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return null;

    }

    private void tableAbsensi() {
        try {
            konek();
            Object header[] = {"NO","NIP", "KODE BULAN", "BULAN", "TAHUN", "HADIR", "SAKIT",
                "IZIN", "ALPA", "CUTI", "TUGAS LUAR", "LEMBUR", "TOTAL SEBULAN"};
            DefaultTableModel data = new DefaultTableModel(null, header);
            tbJumlah.setModel(data);

            String query = "SELECT * FROM `dbabsensi`.`vJumlah`";
            rs = st.executeQuery(query);
            while (rs.next()) {
                String kolom1 = rs.getString("noUrut");
                String kolom2 = rs.getString("nip");
                String kolom3 = rs.getString("kdBulan");
                String kolom4 = rs.getString("nmBulan");
                String kolom5 = rs.getString("tahun");
                String kolom6 = rs.getString("jHadir");
                String kolom7 = rs.getString("jSakit");
                String kolom8 = rs.getString("jIzin");
                String kolom9 = rs.getString("jTnpKeterangan");
                String kolom10 = rs.getString("jCuti");
                String kolom11 = rs.getString("jLembur");
                String kolom12 = rs.getString("jTugas");
                String kolom13 = rs.getString("ttlSebulan");

                String kolom[] = {kolom1,kolom2, kolom3, kolom4, kolom5, kolom6,
                    kolom7, kolom8, kolom9, kolom10, kolom11, kolom12,kolom13};
                data.addRow(kolom);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFrame_Jumlah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inFrame_Jumlah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void tambahJumlah() {
        jumlah = new jumlahEntity();
        int hdr = (int) spHadir.getValue();
        jumlah.setJmlHadir(hdr);
        int skt = (int) spSakit.getValue();
        jumlah.setJmlSakit(skt);
        int izn = (int) spIzin.getValue();
        jumlah.setJmlIzin(izn);
        int alp = (int) spAlpa.getValue();
        jumlah.setJmlTnpKeterangan(alp);
        int ct = (int) spCuti.getValue();
        jumlah.setJmlCuti(ct);
        int lbr = (int) spLembur.getValue();
        jumlah.setJmlTugas(lbr);
        int tgs = (int) spTugas.getValue();
        jumlah.setJmlLembur(tgs);

        // hitung jumlah absensi sebulan
        int total = (hdr + skt + izn + alp + ct + tgs + lbr);

        jumlah.setTotalBulan(total);

        jumlah.setNip(cbxNip_jml.getSelectedItem().toString());
        jumlah.setKdBulan(cbxKode_bulan.getSelectedIndex());
        jumlah.setTahun(Integer.valueOf(txTahun_jml.getText()));
        dbKoneksi.getJumlahDao().saveJumlah(jumlah);
    }

    private void ubahJumlah() {
        jumlah = new jumlahEntity();
        
        int hdr = (int) spHadir.getValue();
        jumlah.setJmlHadir(hdr);
        int skt = (int) spSakit.getValue();
        jumlah.setJmlSakit(skt);
        int izn = (int) spIzin.getValue();
        jumlah.setJmlIzin(izn);
        int alp = (int) spAlpa.getValue();
        jumlah.setJmlTnpKeterangan(alp);
        int ct = (int) spCuti.getValue();
        jumlah.setJmlCuti(ct);
        int lbr = (int) spLembur.getValue();
        jumlah.setJmlTugas(lbr);
        int tgs = (int) spTugas.getValue();
        jumlah.setJmlLembur(tgs);

        // hitung jumlah absensi sebulan
        int total = (hdr + skt + izn + alp + ct + tgs + lbr);

        jumlah.setTotalBulan(total);

        jumlah.setNip(cbxNip_jml.getSelectedItem().toString());
        jumlah.setKdBulan(cbxKode_bulan.getSelectedIndex());
        jumlah.setTahun(Integer.valueOf(txTahun_jml.getText()));
        jumlah.setNo_Urut(Integer.valueOf(lnNo_Urut.getText()));

        dbKoneksi.getJumlahDao().updateJumlah(jumlah);
        //lbNom.hide();
        //lnNo_Urut.hide();
    }

    private void hapusJumlah() {
        jumlah = new jumlahEntity();
        dbKoneksi.getJumlahDao().deleteJumlah(jumlah);
        lbNom.hide();
        lnNo_Urut.hide();
    }

    private void tambahBulan() {

        bulan = new bulanEntity();
        bulan.setKdBulan(cbxKode_bulan.getSelectedIndex());
        bulan.setNmBulan(txNmBulan_jml.getText());
        bulan.setTahun(Integer.parseInt(txTahun_jml.getText()));
        //bulan.setkdJumlah(Integer.parseInt(rs.getString("kdJumlah")));

        dbKoneksi.getBulanDao().saveBulan(bulan);
    }

    private void ubahBulan() {

        bulan = new bulanEntity();
        bulan.setKdBulan(cbxKode_bulan.getSelectedIndex());
        bulan.setNmBulan(txNmBulan_jml.getText());
        bulan.setTahun(Integer.parseInt(txTahun_jml.getText()));

        dbKoneksi.getBulanDao().updateBulan(bulan);
    }

    private void hapusBulan() {

        bulan = new bulanEntity();
        bulan.setKdBulan(cbxKode_bulan.getSelectedIndex());
        bulan.setNmBulan(txNmBulan_jml.getText());
        bulan.setTahun(Integer.parseInt(txTahun_jml.getText()));

        dbKoneksi.getBulanDao().deleteBulan(bulan);
    }

    private void clearForm() {
        lnNo_Urut.setText("");
        tbJumlah.setSelectionMode(0);
        cbxNip_jml.setSelectedIndex(0);
        cbxKode_bulan.setSelectedIndex(0);
        txNmBulan_jml.setText("");
        txTahun_jml.setText("");
        spHadir.setValue(0);
        spSakit.setValue(0);
        spIzin.setValue(0);
        spAlpa.setValue(0);
        spCuti.setValue(0);
        spLembur.setValue(0);
        spTugas.setValue(0);
        txKet_jml.setText("");
        txCari_jml.setText("");
    }

    private void cariDataJumlah() {
        try {
            konek();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("NO");
            model.addColumn("NIP");
            model.addColumn("KODE BULAN");
            model.addColumn("BULAN");
            model.addColumn("TAHUN");
            model.addColumn("HADIR");
            model.addColumn("SAKIT");
            model.addColumn("IZIN");
            model.addColumn("ALPA");
            model.addColumn("CUTI");
            model.addColumn("LEMBUR");
            model.addColumn("TUGAS LUAR");
            model.addColumn("TOTAL");

            if (txCari_jml.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Anda belum memasukan nip pegawai yang anda ingin cari!", "Informasi", JOptionPane.WARNING_MESSAGE);
            } else {
                String sql = "SELECT * FROM vJumlah WHERE nip LIKE'%" + txCari_jml.getText() + "%'";

                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("noUrut"),
                        rs.getString("nip"),
                        rs.getString("kdBulan"),
                        rs.getString("nmBulan"),
                        rs.getString("tahun"),
                        rs.getString("jHadir"),
                        rs.getString("jSakit"),
                        rs.getString("jIzin"),
                        rs.getString("jTnpKeterangan"),
                        rs.getString("jCuti"),
                        rs.getString("jLembur"),
                        rs.getString("jTugas"),
                        rs.getString("ttlSebulan")
                    });

                    tbJumlah.setModel(model);
                    btBatal_jml.setEnabled(true);
                    tbJumlah.setEnabled(true);
                    
                    lbNom.show(true);
                    lnNo_Urut.show(true);
                }
            }
        } catch (SQLException | ClassNotFoundException | HeadlessException e) {
            e.getStackTrace();
            
            JOptionPane.showMessageDialog(rootPane, "Nip yang anda masukan tidak terdaftar!", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }
}
