/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.KeyEvent;

/**
 *
 * @author asus
 */
public class inFrame_Kalkulator extends javax.swing.JInternalFrame {

    // variabel untuk kalkulator
    private double nomPertama, nomKedua, hasil;
    private String operator;

    public inFrame_Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btEquals = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        btBackspace = new javax.swing.JButton();
        txField_Input = new javax.swing.JTextField();
        btTambah = new javax.swing.JButton();
        btKali = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btBagi = new javax.swing.JButton();
        btKurang = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        btTitik = new javax.swing.JButton();

        setClosable(true);
        setTitle("Kalkulator");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Calculator_20px.png"))); // NOI18N

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel6.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 208, 49, 35));

        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel6.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 162, 50, 35));

        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel6.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 208, 50, 35));

        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel6.add(bt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 254, 49, 35));

        btEquals.setText("=");
        btEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEqualsActionPerformed(evt);
            }
        });
        jPanel6.add(btEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 254, 108, 35));

        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel6.add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 162, 49, 35));

        btBackspace.setText("");
        btBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackspaceActionPerformed(evt);
            }
        });
        jPanel6.add(btBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 70, 49, 35));

        txField_Input.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txField_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txField_InputKeyTyped(evt);
            }
        });
        jPanel6.add(txField_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 226, 40));

        btTambah.setText("+");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        jPanel6.add(btTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 70, 49, 35));

        btKali.setText("*");
        btKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKaliActionPerformed(evt);
            }
        });
        jPanel6.add(btKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 162, 49, 35));

        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel6.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 116, 49, 35));

        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel6.add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 116, 50, 35));

        btBagi.setText("/");
        btBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBagiActionPerformed(evt);
            }
        });
        jPanel6.add(btBagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 208, 49, 35));

        btKurang.setText("-");
        btKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKurangActionPerformed(evt);
            }
        });
        jPanel6.add(btKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 116, 49, 35));

        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel6.add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 162, 49, 35));

        jButton3.setText("+/-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 35));

        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel6.add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 116, 49, 35));

        btClear.setText("C");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel6.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 49, 35));

        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel6.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 208, 49, 35));

        btTitik.setText(".");
        btTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTitikActionPerformed(evt);
            }
        });
        jPanel6.add(btTitik, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 254, 49, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        String number = txField_Input.getText() + bt1.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        String number = txField_Input.getText() + bt6.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        String number = txField_Input.getText() + bt3.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        String number = txField_Input.getText() + bt0.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt0ActionPerformed

    private void btEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEqualsActionPerformed
        String jawab;
        nomKedua = Double.parseDouble(txField_Input.getText());
        if (operator == "+") {
            hasil = nomPertama + nomKedua;
            jawab = String.format("%.0f", hasil);
            txField_Input.setText(jawab);
        } else if (operator == "-") {
            hasil = nomPertama - nomKedua;
            jawab = String.format("%.0f", hasil);
            txField_Input.setText(jawab);
        } else if (operator == "*") {
            hasil = nomPertama * nomKedua;
            jawab = String.format("%.0f", hasil);
            txField_Input.setText(jawab);
        } else if (operator == "/") {
            hasil = nomPertama / nomKedua;
            jawab = String.format("%.0f", hasil);
            txField_Input.setText(jawab);
        } else if (operator == "%") {
            hasil = nomPertama % nomKedua;
            jawab = String.format("%.0f", hasil);
            txField_Input.setText(jawab);
        }
    }//GEN-LAST:event_btEqualsActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        String number = txField_Input.getText() + bt5.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt5ActionPerformed

    private void btBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackspaceActionPerformed
        String hapus = null;

        if (txField_Input.getText().length() > 0) {
            StringBuilder strB = new StringBuilder(txField_Input.getText());
            strB.deleteCharAt(txField_Input.getText().length() - 1);
            hapus = strB.toString();
            txField_Input.setText(hapus);
        }
    }//GEN-LAST:event_btBackspaceActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        nomPertama = Double.parseDouble(txField_Input.getText());
        txField_Input.setText("");
        operator = "+";
    }//GEN-LAST:event_btTambahActionPerformed

    private void btKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKaliActionPerformed
        nomPertama = Double.parseDouble(txField_Input.getText());
        txField_Input.setText("");
        operator = "*";
    }//GEN-LAST:event_btKaliActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        String number = txField_Input.getText() + bt7.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        String number = txField_Input.getText() + bt9.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt9ActionPerformed

    private void btBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBagiActionPerformed
        nomPertama = Double.parseDouble(txField_Input.getText());
        txField_Input.setText("");
        operator = "/";
    }//GEN-LAST:event_btBagiActionPerformed

    private void btKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKurangActionPerformed
        nomPertama = Double.parseDouble(txField_Input.getText());
        txField_Input.setText("");
        operator = "-";
    }//GEN-LAST:event_btKurangActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        String number = txField_Input.getText() + bt4.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double ops = Double.parseDouble(String.valueOf(txField_Input.getText()));
        ops = ops * (-1);
        txField_Input.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        String number = txField_Input.getText() + bt8.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt8ActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        txField_Input.setText(null);
    }//GEN-LAST:event_btClearActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        String number = txField_Input.getText() + bt2.getText();
        txField_Input.setText(number);
    }//GEN-LAST:event_bt2ActionPerformed

    private void btTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTitikActionPerformed
        txField_Input.setText(txField_Input.getText() + btTitik.getText());
    }//GEN-LAST:event_btTitikActionPerformed

    private void txField_InputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txField_InputKeyTyped
        // DISINI HANYA MENERIMA ANGKA
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txField_InputKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btBackspace;
    private javax.swing.JButton btBagi;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btEquals;
    private javax.swing.JButton btKali;
    private javax.swing.JButton btKurang;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btTitik;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txField_Input;
    // End of variables declaration//GEN-END:variables

}
