/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.dbKoneksi;
import model.alamatEntity;
import model.pegawaiEntity;

/**
 *
 * @author asus
 */
public class inFrame_Pegawai extends javax.swing.JInternalFrame {

    private ResultSet rs;
    private Statement st;
    private Connection conn;
    private PreparedStatement pst;

    private List<pegawaiEntity> listPegawai;

    private alamatEntity alamat;
    private pegawaiEntity pegawai;

    public inFrame_Pegawai() {
        initComponents();

        buttonGroup1.add(rbPria_pgw);
        buttonGroup1.add(rbWanita_pgw);

        tableData();
    }


    private void clearPegawai() {
        txCariPegawai.setText("");
        txNip_pgw.setText("");
        txNama_pgw.setText("");
        rbPria_pgw.setSelected(false);
        rbWanita_pgw.setSelected(false);
        txT4Lahir_pgw.setText("");
        dtTanggal_lahir.setDate(null);
        cbxPend_pgw.setSelectedIndex(0);
        txJab_pgw.setText("");
        cbxGolongan.setSelectedIndex(0);
        txDept_pgw.setText("");
        txTelp_pgw.setText("");
        txNoJalan.setText("");
        txAlamatJalan.setText("");
        txKota.setText("");
        txProvinsi.setText("");
        tbPegawai.setSelectionMode(0);
    }


    public void setInput_Num(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txNip_pgw = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txNama_pgw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txJab_pgw = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxGolongan = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txT4Lahir_pgw = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxPend_pgw = new javax.swing.JComboBox();
        dtTanggal_lahir = new com.toedter.calendar.JDateChooser();
        rbWanita_pgw = new javax.swing.JRadioButton();
        rbPria_pgw = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txDept_pgw = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txTelp_pgw = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txNoJalan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txAlamatJalan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txKota = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txProvinsi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPegawai = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btCari_pgw = new javax.swing.JButton();
        txCariPegawai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btSimpanPegawai = new javax.swing.JButton();
        btUbah_pgw = new javax.swing.JButton();
        btHapus_pgw = new javax.swing.JButton();
        btBatal_pgw = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Pegawai");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Admin_20px.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nip");

        txNip_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txNip_pgw.setToolTipText("Masukan NIP Pegawai");
        txNip_pgw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNip_pgwKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        txNama_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jabatan");

        txJab_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Golongan");

        cbxGolongan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxGolongan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Golongan", "I/a", "I/b", "I/c", "I/d", "II/a", "II/b", "II/c", "II/d", "III/a", "III/b", "III/c", "III/d", "IV/a", "IV/b", "IV/c", "IV/d" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tempat Lahir");

        txT4Lahir_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Tanggal Lahir");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Pendidikan");

        cbxPend_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxPend_pgw.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Pendidikan", "SD", "SMP", "SMA", "D3", "S1", "S2", "S3", " " }));

        rbWanita_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbWanita_pgw.setText("Wanita");
        rbWanita_pgw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rbPria_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPria_pgw.setText("Pria");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Departement");

        txDept_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Telepon");

        txTelp_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txTelp_pgw.setToolTipText("Masukan nomor telepon");
        txTelp_pgw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txTelp_pgwKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("No rumah");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Alamat Jalan");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Kota");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Provinsi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txNip_pgw))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txNama_pgw))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txT4Lahir_pgw))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dtTanggal_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txJab_pgw))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txDept_pgw))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txTelp_pgw))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxPend_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbPria_pgw)
                                .addGap(18, 18, 18)
                                .addComponent(rbWanita_pgw))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txNoJalan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txAlamatJalan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txKota))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txProvinsi)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNip_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNama_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbWanita_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPria_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txT4Lahir_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dtTanggal_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPend_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txJab_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxGolongan)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txDept_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txTelp_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txNoJalan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txAlamatJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txKota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbPegawai.setAutoCreateRowSorter(true);
        tbPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPegawai.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbPegawai.setSelectionForeground(new java.awt.Color(51, 255, 0));
        tbPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPegawai);

        btCari_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCari_pgw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Search_20px.png"))); // NOI18N
        btCari_pgw.setText("Cari...");
        btCari_pgw.setToolTipText("Tekan tombol cari untuk mencari data berdasarkan nip pegawai");
        btCari_pgw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCari_pgwActionPerformed(evt);
            }
        });

        txCariPegawai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txCariPegawai.setToolTipText("Masukan nip pegawai yang anda ingin cari");
        txCariPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCariPegawaiActionPerformed(evt);
            }
        });
        txCariPegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCariPegawaiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCari_pgw)
                        .addGap(18, 18, 18)
                        .addComponent(txCariPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txCariPegawai)
                    .addComponent(btCari_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btSimpanPegawai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSimpanPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Save_as_20px.png"))); // NOI18N
        btSimpanPegawai.setText("Simpan");
        btSimpanPegawai.setToolTipText("Simpan data pegawai ke penyimpanan data");
        btSimpanPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanPegawaiActionPerformed(evt);
            }
        });

        btUbah_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btUbah_pgw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Update_20px.png"))); // NOI18N
        btUbah_pgw.setText("Ubah");
        btUbah_pgw.setToolTipText("Perbaharui data pegawai yang telah diubah");
        btUbah_pgw.setEnabled(false);
        btUbah_pgw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbah_pgwActionPerformed(evt);
            }
        });

        btHapus_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btHapus_pgw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Trash_Can_20px.png"))); // NOI18N
        btHapus_pgw.setText("Hapus");
        btHapus_pgw.setToolTipText("Hapus data pegawai dari penyimpanan");
        btHapus_pgw.setEnabled(false);
        btHapus_pgw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapus_pgwActionPerformed(evt);
            }
        });

        btBatal_pgw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btBatal_pgw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Delete_20px.png"))); // NOI18N
        btBatal_pgw.setText("Batal");
        btBatal_pgw.setToolTipText("Batalkan penambahan atau perubahan data pegawai");
        btBatal_pgw.setEnabled(false);
        btBatal_pgw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatal_pgwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btSimpanPegawai)
                .addGap(18, 18, 18)
                .addComponent(btUbah_pgw)
                .addGap(23, 23, 23)
                .addComponent(btHapus_pgw)
                .addGap(18, 18, 18)
                .addComponent(btBatal_pgw)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUbah_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHapus_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSimpanPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBatal_pgw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanPegawaiActionPerformed
        pegawai = new pegawaiEntity();
        pegawai.setNIP(txNip_pgw.getText());
        pegawai.setNama(txNama_pgw.getText());
        if (rbPria_pgw.isSelected()) {
            pegawai.setJK("Pria");
        } else {
            pegawai.setJK("Wanita");
        }
        pegawai.setTempatLahir(txT4Lahir_pgw.getText());
        pegawai.setTglLahir(dtTanggal_lahir.getDate());
        pegawai.setPendidikan(cbxPend_pgw.getSelectedItem().toString());
        pegawai.setJabatan(txJab_pgw.getText());
        pegawai.setGolongan(cbxGolongan.getSelectedItem().toString());
        pegawai.setDepartement(txDept_pgw.getText());
        pegawai.setTelepon(txTelp_pgw.getText());
        pegawai.setNo_Rumah(Integer.parseInt(txNoJalan.getText()));

        alamat = new alamatEntity();
        alamat.setNo_Rumah(Integer.parseInt(txNoJalan.getText()));
        alamat.setNama_jalan(txAlamatJalan.getText());
        alamat.setKota(txKota.getText());
        alamat.setPrivinsi(txProvinsi.getText());

        dbKoneksi.getAlamatDao().saveAlamat(alamat);

        dbKoneksi.getPegawaiDao().savePegawai(pegawai);
        tableData();
        clearPegawai();
    }//GEN-LAST:event_btSimpanPegawaiActionPerformed

    private void btUbah_pgwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbah_pgwActionPerformed
        pegawai = new pegawaiEntity();
        pegawai.setNIP(txNip_pgw.getText());
        pegawai.setNama(txNama_pgw.getText());
        if (rbPria_pgw.isSelected()) {
            pegawai.setJK("Pria");
        } else {
            pegawai.setJK("Wanita");
        }
        pegawai.setTempatLahir(txT4Lahir_pgw.getText());
        pegawai.setTglLahir(dtTanggal_lahir.getDate());
        pegawai.setPendidikan(cbxPend_pgw.getSelectedItem().toString());
        pegawai.setJabatan(txJab_pgw.getText());
        pegawai.setGolongan(cbxGolongan.getSelectedItem().toString());
        pegawai.setDepartement(txDept_pgw.getText());
        pegawai.setTelepon(txTelp_pgw.getText());
        pegawai.setNo_Rumah(Integer.valueOf(txNoJalan.getText()));

        alamat = new alamatEntity();
        alamat.setNo_Rumah(Integer.valueOf(txNoJalan.getText()));
        alamat.setNama_jalan(txAlamatJalan.getText());
        alamat.setKota(txKota.getText());
        alamat.setPrivinsi(txProvinsi.getText());

        dbKoneksi.getAlamatDao().updateAlamat(alamat);

        dbKoneksi.getPegawaiDao().updatePegawai(pegawai);
        tableData();
        clearPegawai();

        btSimpanPegawai.setEnabled(true);
        btUbah_pgw.setEnabled(false);
        btHapus_pgw.setEnabled(false);
        btBatal_pgw.setEnabled(false);
    }//GEN-LAST:event_btUbah_pgwActionPerformed

    private void btHapus_pgwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapus_pgwActionPerformed
        dbKoneksi.getPegawaiDao().deletePegawai(pegawai);
        tableData();
        clearPegawai();

        btSimpanPegawai.setEnabled(true);
        btUbah_pgw.setEnabled(false);
        btHapus_pgw.setEnabled(false);
        btBatal_pgw.setEnabled(false);
    }//GEN-LAST:event_btHapus_pgwActionPerformed

    private void btBatal_pgwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatal_pgwActionPerformed
        clearPegawai();
        tableData();
        
        btSimpanPegawai.setEnabled(true);
        btUbah_pgw.setEnabled(false);
        btHapus_pgw.setEnabled(false);
        btBatal_pgw.setEnabled(false);
    }//GEN-LAST:event_btBatal_pgwActionPerformed

    private void txNip_pgwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNip_pgwKeyTyped
        // DISINI HANYA MENERIMA ANGKA
        setInput_Num(evt);
    }//GEN-LAST:event_txNip_pgwKeyTyped

    private void txTelp_pgwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTelp_pgwKeyTyped
        // DISINI HANYA MENERIMA ANGKA
        setInput_Num(evt);
    }//GEN-LAST:event_txTelp_pgwKeyTyped

    private void txCariPegawaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCariPegawaiKeyTyped
        // DISINI HANYA MENERIMA ANGKA
        setInput_Num(evt);
    }//GEN-LAST:event_txCariPegawaiKeyTyped

    private void btCari_pgwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCari_pgwActionPerformed
        
        if (txCariPegawai.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nip pegawai belum diisi!", "Gagal", JOptionPane.WARNING_MESSAGE);
        } else {
            cariPegawai();
            btBatal_pgw.setEnabled(true);
        }
    }//GEN-LAST:event_btCari_pgwActionPerformed

    private void tbPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPegawaiMouseClicked
        TableModel model  = tbPegawai.getModel();
        int row = tbPegawai.getSelectedRow();
        
        txNip_pgw.setText(String.valueOf(model.getValueAt(row, 0)));
        txNama_pgw.setText(String.valueOf(model.getValueAt(row, 1)));
        String sex = model.getValueAt(row, 2).toString();
        if(rbPria_pgw.getText().equalsIgnoreCase("Pria")) {
            rbPria_pgw.setSelected(true);
        } else {
            rbWanita_pgw.setSelected(true);
        }
        txT4Lahir_pgw.setText(String.valueOf(model.getValueAt(row, 3)));
        dtTanggal_lahir.setDate(Date.valueOf(model.getValueAt(row, 4).toString()));
        cbxPend_pgw.setSelectedItem(String.valueOf(model.getValueAt(row, 5)));
        txJab_pgw.setText(model.getValueAt(row, 6).toString());
        cbxGolongan.setSelectedItem(String.valueOf(model.getValueAt(row, 7)));
        txDept_pgw.setText(model.getValueAt(row, 8).toString());
        txTelp_pgw.setText(model.getValueAt(row, 9).toString());
        txAlamatJalan.setText(model.getValueAt(row, 10).toString());
        txNoJalan.setText(model.getValueAt(row, 11).toString());
        txKota.setText(model.getValueAt(row, 12).toString());
        txProvinsi.setText(model.getValueAt(row, 13).toString());
        
        btSimpanPegawai.setEnabled(false);
        btUbah_pgw.setEnabled(true);
        btHapus_pgw.setEnabled(true);
        btBatal_pgw.setEnabled(true);
    }//GEN-LAST:event_tbPegawaiMouseClicked

    private void txCariPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCariPegawaiActionPerformed
        if (txCariPegawai.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nip pegawai belum diisi!", "Gagal", JOptionPane.WARNING_MESSAGE);
        } else {
            cariPegawai();
            btBatal_pgw.setEnabled(true); 
        }
    }//GEN-LAST:event_txCariPegawaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal_pgw;
    private javax.swing.JButton btCari_pgw;
    private javax.swing.JButton btHapus_pgw;
    private javax.swing.JButton btSimpanPegawai;
    private javax.swing.JButton btUbah_pgw;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxGolongan;
    private javax.swing.JComboBox cbxPend_pgw;
    private com.toedter.calendar.JDateChooser dtTanggal_lahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rbPria_pgw;
    private javax.swing.JRadioButton rbWanita_pgw;
    private javax.swing.JTable tbPegawai;
    private javax.swing.JTextField txAlamatJalan;
    private javax.swing.JTextField txCariPegawai;
    private javax.swing.JTextField txDept_pgw;
    private javax.swing.JTextField txJab_pgw;
    private javax.swing.JTextField txKota;
    private javax.swing.JTextField txNama_pgw;
    private javax.swing.JTextField txNip_pgw;
    private javax.swing.JTextField txNoJalan;
    private javax.swing.JTextField txProvinsi;
    private javax.swing.JTextField txT4Lahir_pgw;
    private javax.swing.JTextField txTelp_pgw;
    // End of variables declaration//GEN-END:variables

    public Connection konek() throws SQLException, ClassNotFoundException {
        try {
            //
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbAbsensi", "root", "root");
            st = conn.createStatement();
            pst = conn.prepareStatement("SET FOREIGN_KEY_CHECKs=0");
            pst.executeQuery();

            return conn;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return null;
    }
    
    private void cariPegawai() {
        try {
            konek();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("NIP");
            model.addColumn("NAMA");
            model.addColumn("JK");
            model.addColumn("TEMPAT LAHIR");
            model.addColumn("TANGGAL LAHIR");
            model.addColumn("PENDIDIKAN");
            model.addColumn("JABATAN");
            model.addColumn("GOLONGAN");
            model.addColumn("DEPARTEMENT");
            model.addColumn("TELEPON");
            model.addColumn("ALAMAT JALAN");
            model.addColumn("NOMOR RUMAH");
            model.addColumn("KOTA");
            model.addColumn("PROVINSI");

            if (txCariPegawai.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Anda belum memasukan nip pegawai yang anda ingin cari!", "Informasi", JOptionPane.WARNING_MESSAGE);
            } else {
                String sql = "SELECT * FROM vPEGAWAI WHERE nip LIKE'%" + txCariPegawai.getText() + "%'";

                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("nip"),
                        rs.getString("nama"),
                        rs.getString("jk"),
                        rs.getString("t4Lahir"),
                        rs.getString("tglLahir"),
                        rs.getString("pendidikan"),
                        rs.getString("jab"),
                        rs.getString("gol"),
                        rs.getString("dept"),
                        rs.getString("telp"),
                        rs.getString("nmJalan"),
                        rs.getString("noRumah"),
                        rs.getString("kota"),
                        rs.getString("prov")
                    });

                    tbPegawai.setModel(model);
                }
            }
        } catch (SQLException | ClassNotFoundException | HeadlessException e) {
            e.getStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nip yang anda masukan tidak terdaftar!", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void tableData() {
        try {
            konek();
            Object header[] = {"NIP", "NAMA", "JK", "TEMPAT LAHIR", "TANGGAL LAHIR", "PENDIDIKAN",
                "JABATAN", "GOLONGAN", "DEPARTEMENT", "TELEPON", "ALAMAT JALAN", "NO RUMAH", "KOTA", "PROVINSI"};
            DefaultTableModel data = new DefaultTableModel(null, header);
            tbPegawai.setModel(data);

            String query = "SELECT\n"
                    + "    `tbpegawai`.`nip`\n"
                    + "    , `tbpegawai`.`nama`\n"
                    + "    , `tbpegawai`.`jk`\n"
                    + "    , `tbpegawai`.`pendidikan`\n"
                    + "    , `tbpegawai`.`jab`\n"
                    + "    , `tbpegawai`.`gol`\n"
                    + "    , `tbpegawai`.`dept`\n"
                    + "    , `tbpegawai`.`t4Lahir`\n"
                    + "    , `tbpegawai`.`tglLahir`\n"
                    + "    , `tbpegawai`.`telp`\n"
                    + "    , `tbpegawai`.`noRumah`\n"
                    + "    , `tbalamat`.`nmJalan`\n"
                    + "    , `tbpegawai`.`noRumah`\n"
                    + "    , `tbalamat`.`kota`\n"
                    + "    , `tbalamat`.`prov`\n"
                    + "FROM\n"
                    + "    `dbabsensi`.`tbpegawai`\n"
                    + "    INNER JOIN `dbabsensi`.`tbalamat` \n"
                    + "        ON (`tbpegawai`.`noRumah` = `tbalamat`.`noRumah`)";
            rs = st.executeQuery(query);
            while (rs.next()) {
                String kolom1 = rs.getString("nip");
                String kolom2 = rs.getString("nama");
                String kolom3 = rs.getString("jk");
                String kolom4 = rs.getString("t4Lahir");
                String kolom5 = rs.getString("tglLahir");
                String kolom6 = rs.getString("pendidikan");
                String kolom7 = rs.getString("jab");
                String kolom8 = rs.getString("gol");
                String kolom9 = rs.getString("dept");
                String kolom10 = rs.getString("telp");
                String kolom11 = rs.getString("nmJalan");
                String kolom12 = rs.getString("noRumah");
                String kolom13 = rs.getString("kota");
                String kolom14 = rs.getString("prov");

                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6,
                    kolom7, kolom8, kolom9, kolom10, kolom11, kolom12,kolom13,kolom14};
                data.addRow(kolom);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFrame_Jumlah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inFrame_Jumlah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
