/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.dbKoneksi;

/**
 *
 * @author asus
 */
public class inFrame_Lihat extends javax.swing.JInternalFrame {

    private ResultSet rst;
    private Statement st;
    private Connection conn;
    private PreparedStatement pst;

    public inFrame_Lihat() {
        initComponents();

        dbKoneksi.bindNIPtoLihat(cbxNIP_Lihat);
        txTahun_Lihat.setToolTipText("Masukan tahun sebanyak empat angka!");
    }

    public void setInput_Num(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        cbxNIP_Lihat = new javax.swing.JComboBox();
        jLabel72 = new javax.swing.JLabel();
        cbxBulan_Lihat = new javax.swing.JComboBox();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        btTampilkan_Lihat = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel75 = new javax.swing.JLabel();
        lbJK = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        lbNIP_Lihat = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        lbPend_Lihat = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        lbNama_Lihat = new javax.swing.JLabel();
        lbT4Lahir_Lihat = new javax.swing.JLabel();
        lbDept_Lihat = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        lbJab_Lihat = new javax.swing.JLabel();
        lbGol_Lihat = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        lbTelp_Lihat = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        lbTglLahir_Lihat = new javax.swing.JLabel();
        lbBulan_Lihat = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        lbJmlHadir_Lihat = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jmlSakit_Lihat = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        lbJmlIzin_Lihat = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        lbAlamat_Lihat = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        lbjmlAlpa_Lihat = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        lbJmlCuti_Lihat = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        lbJmlTugas_Lihat = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        lbJmlLembur_Lihat = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        lbTotal_Lihat = new javax.swing.JLabel();
        txTahun_Lihat = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Detail");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Show_Property_20px.png"))); // NOI18N

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cbxNIP_Lihat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Nip" }));
        cbxNIP_Lihat.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbxNIP_LihatPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel72.setText("Pilih NIP Pegawai : ");

        cbxBulan_Lihat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih bulan" }));
        cbxBulan_Lihat.setEnabled(false);

        jLabel73.setText("Bulan : ");

        jLabel74.setText("Tahun : ");

        btTampilkan_Lihat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Show_Property_20px.png"))); // NOI18N
        btTampilkan_Lihat.setText("Tampilkan Data Pegawai");
        btTampilkan_Lihat.setEnabled(false);
        btTampilkan_Lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTampilkan_LihatActionPerformed(evt);
            }
        });

        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel75.setText("Jenis Kelamin");

        lbJK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel77.setText("Nip Pegawai");

        lbNIP_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel79.setText("Pendidikan");

        lbPend_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel81.setText("Nama");

        lbNama_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbT4Lahir_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbDept_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel85.setText("Departement");

        jLabel104.setText("Tempat Lahir");

        jLabel105.setText("Golongan");

        jLabel106.setText("Jabatan");

        lbJab_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbGol_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel109.setText("Telepon");

        lbTelp_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel111.setText("Tanggal Lahir");

        lbTglLahir_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbBulan_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel115.setText("Jumlah Hadir");

        lbJmlHadir_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlHadir_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel117.setText("Jumlah Sakit");

        jmlSakit_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlSakit_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel119.setText("Jumlah Izin");

        lbJmlIzin_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlIzin_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel121.setText("Alamat");

        lbAlamat_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel123.setText("Jumlah Alpa");

        lbjmlAlpa_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbjmlAlpa_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel125.setText("Jumlah Cuti");

        lbJmlCuti_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlCuti_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel127.setText("Tugas Luar");

        lbJmlTugas_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlTugas_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel129.setText("Jumlah Lembur");

        lbJmlLembur_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlLembur_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel131.setText("Jumlah total sebulan");

        lbTotal_Lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txTahun_Lihat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txTahun_Lihat.setEnabled(false);
        txTahun_Lihat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txTahun_LihatKeyTyped(evt);
            }
        });

        jLabel113.setText("Pada Bulan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(jLabel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(jLabel109, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel121, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbT4Lahir_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTglLahir_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbJK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbNama_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbNIP_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbGol_Lihat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                        .addComponent(lbPend_Lihat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbJab_Lihat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbDept_Lihat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbAlamat_Lihat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTelp_Lihat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel131, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jLabel129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel117, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel127, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lbJmlLembur_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addComponent(lbJmlHadir_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jmlSakit_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbJmlIzin_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbjmlAlpa_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbJmlTugas_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbJmlCuti_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbBulan_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(lbTotal_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btTampilkan_Lihat))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel72)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxNIP_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(jLabel73)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxBulan_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel74)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txTahun_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNIP_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBulan_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTahun_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btTampilkan_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBulan_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJmlHadir_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmlSakit_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJmlIzin_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel119, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbjmlAlpa_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJmlCuti_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel125, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJmlTugas_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel127, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJmlLembur_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTotal_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel131, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbJK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbT4Lahir_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTglLahir_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbPend_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel106, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbJab_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbGol_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbDept_Lihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTelp_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbAlamat_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lbNIP_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbNama_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator19)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNIP_LihatPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbxNIP_LihatPopupMenuWillBecomeInvisible
        getBulan();
        btTampilkan_Lihat.setEnabled(true);
        cbxBulan_Lihat.setEnabled(true);
        txTahun_Lihat.setEnabled(true);

        if (cbxNIP_Lihat.getSelectedIndex() == 0) {
            String bln = "Pilih bulan";
            cbxBulan_Lihat.removeAllItems();
            cbxBulan_Lihat.addItem(bln);
            lbJK.setText("");
            lbNIP_Lihat.setText("");
            lbNama_Lihat.setText("");
            lbPend_Lihat.setText("");
            lbJab_Lihat.setText("");
            lbGol_Lihat.setText("");
            lbDept_Lihat.setText("");
            lbT4Lahir_Lihat.setText("");
            lbTglLahir_Lihat.setText("");
            lbTelp_Lihat.setText("");
            lbAlamat_Lihat.setText("");
            lbBulan_Lihat.setText("");
            lbJmlHadir_Lihat.setText("");
            jmlSakit_Lihat.setText("");
            lbJmlIzin_Lihat.setText("");
            lbjmlAlpa_Lihat.setText("");
            lbJmlCuti_Lihat.setText("");
            lbJmlTugas_Lihat.setText("");
            lbJmlLembur_Lihat.setText("");
            lbTotal_Lihat.setText("");
            txTahun_Lihat.setText("");
            btTampilkan_Lihat.setEnabled(false);
            cbxBulan_Lihat.setEnabled(false);
            txTahun_Lihat.setEnabled(false);
        }
    }//GEN-LAST:event_cbxNIP_LihatPopupMenuWillBecomeInvisible

    private void btTampilkan_LihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTampilkan_LihatActionPerformed
        // tampilkan data
        lihatData();

        if (cbxNIP_Lihat.getSelectedItem().equals("Pilih Nip") && cbxBulan_Lihat.getSelectedItem().equals("Pilih bulan")) {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btTampilkan_LihatActionPerformed

    private void txTahun_LihatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTahun_LihatKeyTyped
        // DISINI HANYA MENERIMA ANGKA
        setInput_Num(evt);
    }//GEN-LAST:event_txTahun_LihatKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTampilkan_Lihat;
    private javax.swing.JComboBox cbxBulan_Lihat;
    private javax.swing.JComboBox cbxNIP_Lihat;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JLabel jmlSakit_Lihat;
    private javax.swing.JLabel lbAlamat_Lihat;
    private javax.swing.JLabel lbBulan_Lihat;
    private javax.swing.JLabel lbDept_Lihat;
    private javax.swing.JLabel lbGol_Lihat;
    private javax.swing.JLabel lbJK;
    private javax.swing.JLabel lbJab_Lihat;
    private javax.swing.JLabel lbJmlCuti_Lihat;
    private javax.swing.JLabel lbJmlHadir_Lihat;
    private javax.swing.JLabel lbJmlIzin_Lihat;
    private javax.swing.JLabel lbJmlLembur_Lihat;
    private javax.swing.JLabel lbJmlTugas_Lihat;
    private javax.swing.JLabel lbNIP_Lihat;
    private javax.swing.JLabel lbNama_Lihat;
    private javax.swing.JLabel lbPend_Lihat;
    private javax.swing.JLabel lbT4Lahir_Lihat;
    private javax.swing.JLabel lbTelp_Lihat;
    private javax.swing.JLabel lbTglLahir_Lihat;
    private javax.swing.JLabel lbTotal_Lihat;
    private javax.swing.JLabel lbjmlAlpa_Lihat;
    private javax.swing.JTextField txTahun_Lihat;
    // End of variables declaration//GEN-END:variables

    public Connection konek() throws SQLException, ClassNotFoundException {
        try {
            //
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbabsensi", "root", "root");
            st = conn.createStatement();
            pst = conn.prepareStatement("SET FOREIGN_KEY_CHECKs=0");
            pst.executeQuery();

            return conn;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return null;
    }

    private void lihatData() {
        try {
            konek();

            String nip = cbxNIP_Lihat.getSelectedItem().toString();
            String buln = cbxBulan_Lihat.getSelectedItem().toString();
            String thn = txTahun_Lihat.getText();
            String query = "SELECT * FROM viewrekap WHERE nip LIKE'" + nip + "' AND nmBulan LIKE'" + buln + "' AND tahun LIKE'" + thn + "'";
            rst = st.executeQuery(query);

            while (rst.next()) {

                String nipp = rst.getString("nip");
                lbNIP_Lihat.setText(" " + nipp);
                String nm = rst.getString("nama");
                lbNama_Lihat.setText(" " + nm);
                String jk = rst.getString("jk");
                lbJK.setText(" " + jk);
                String t4 = rst.getString("t4Lahir");
                lbT4Lahir_Lihat.setText(" " + t4);
                String tglLahir = rst.getString("tglLahir");
                lbTglLahir_Lihat.setText(" " + tglLahir);
                String pen = rst.getString("pendidikan");
                lbPend_Lihat.setText(" " + pen);
                String jbt = rst.getString("jab");
                lbJab_Lihat.setText(" " + jbt);
                String gol = rst.getString("gol");
                lbGol_Lihat.setText(" " + gol);
                String dpt = rst.getString("dept");
                lbDept_Lihat.setText(" " + dpt);
                String tlp = rst.getString("telp");
                lbTelp_Lihat.setText(" " + tlp);
                String jl = rst.getString("nmJalan");
                String rmh = rst.getString("noRumah");
                String kt = rst.getString("kota");
                lbAlamat_Lihat.setText(" " + jl +" " +rmh +", "+kt);
                String bul = rst.getString("nmBulan");
                lbBulan_Lihat.setText(" " + bul);

                // get integer value dari textField jumlah
                int hdr = rst.getInt("jHadir");
                lbJmlHadir_Lihat.setText(String.valueOf(hdr));
                int skt = rst.getInt("jSakit");
                jmlSakit_Lihat.setText(String.valueOf(skt));
                int izn = rst.getInt("jIzin");
                lbJmlIzin_Lihat.setText(String.valueOf(izn));
                int alp = rst.getInt("jTnpKeterangan");
                lbjmlAlpa_Lihat.setText(String.valueOf(alp));
                int cti = rst.getInt("jCuti");
                lbJmlCuti_Lihat.setText(String.valueOf(cti));
                int lbr = rst.getInt("jLembur");
                lbJmlLembur_Lihat.setText(String.valueOf(lbr));
                int tgs = rst.getInt("jTugas");
                lbJmlTugas_Lihat.setText(String.valueOf(tgs));

                int total = (hdr + skt + izn + alp + cti + lbr + tgs);

                // convert tipe integer ke tipe string
                String hh = String.valueOf(total);

                //display hasil jumlah 
                lbTotal_Lihat.setText(hh);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(inFrame_Lihat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getBulan() {
        try {
            konek();
            cbxBulan_Lihat.removeAllItems();

            String nip = cbxNIP_Lihat.getSelectedItem().toString();
            String sql2 = "SELECT * FROM viewrekap WHERE viewrekap.`nip` ='" + nip + "'";
            rst = st.executeQuery(sql2);

            while (rst.next()) {
                String bul = rst.getString("nmBulan");
                cbxBulan_Lihat.addItem(bul);
                String thn = rst.getString("tahun");
                txTahun_Lihat.setText(thn);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(inFrame_Lihat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
