/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author asus
 */
public class inFrame_Rekap extends javax.swing.JInternalFrame {

    private ResultSet rs;
    private Statement st;
    private PreparedStatement pst;
    private Connection conn;

    public inFrame_Rekap() {
        initComponents();
        tableCetak();

        txtCari.setToolTipText("Masukan nip pegawai");
    }

    public void setInput_Num(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbJab_Lihat = new javax.swing.JLabel();
        lbPend_Lihat = new javax.swing.JLabel();
        lbNIP_Lihat = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        lbDept_Lihat = new javax.swing.JLabel();
        lbTglLahir_Lihat = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        lbT4Lahir_Lihat = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        lbGol_Lihat = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        lbJK = new javax.swing.JLabel();
        lbTelp_Lihat = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        lbAlamat_Lihat = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        lbNama_Lihat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTtl_Setahun = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btCariRekap = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btSegarkan = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btRekap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTampil = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rekapitulasi Data Absensi");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Report_Card_20px.png"))); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 210, 238)));

        lbJab_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        lbPend_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        lbNIP_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        jLabel109.setText("Telepon");

        jLabel105.setText("Golongan");

        jLabel77.setText("Nip Pegawai");

        jLabel79.setText("Pendidikan");

        jLabel121.setText("Alamat");

        lbDept_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        lbTglLahir_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        jLabel106.setText("Jabatan");

        lbT4Lahir_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        jLabel75.setText("Jenis Kelamin");

        lbGol_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        jLabel85.setText("Departement");

        lbJK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        lbTelp_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        jLabel111.setText("Tanggal Lahir");

        lbAlamat_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        jLabel81.setText("Nama");

        jLabel104.setText("Tempat Lahir");

        lbNama_Lihat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 241, 248)));

        jLabel1.setText("TOTAL JUMLAH DALAM SETAHUN");

        lbTtl_Setahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTtl_Setahun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 253, 238)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbNIP_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbJab_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbNama_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbGol_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbJK, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbDept_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbT4Lahir_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTelp_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbPend_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(lbTglLahir_Lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbAlamat_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbTtl_Setahun, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNIP_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJab_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNama_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGol_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDept_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbT4Lahir_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelp_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTglLahir_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAlamat_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTtl_Setahun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPend_Lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 279));

        btCariRekap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCariRekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Search_20px.png"))); // NOI18N
        btCariRekap.setText("Cari...");
        btCariRekap.setToolTipText("Cari data pegawai yang ingin anda cetak");
        btCariRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariRekapActionPerformed(evt);
            }
        });

        txtCari.setBackground(new java.awt.Color(240, 240, 240));
        txtCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCari.setToolTipText("Masukan nip disini");
        txtCari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariKeyTyped(evt);
            }
        });

        btSegarkan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSegarkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Refresh_20px.png"))); // NOI18N
        btSegarkan.setText("Segarkan");
        btSegarkan.setToolTipText("Segarkan data");
        btSegarkan.setEnabled(false);
        btSegarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSegarkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSegarkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCariRekap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCari)
                    .addComponent(btCariRekap, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSegarkan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        btRekap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Print_20px.png"))); // NOI18N
        btRekap.setText("Rekap Data Absensi");
        btRekap.setToolTipText("Rekapitulasi data pegawai");
        btRekap.setEnabled(false);
        btRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRekapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRekap)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelTampil.setAutoCreateRowSorter(true);
        tabelTampil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelTampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelTampil.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabelTampil.setEnabled(false);
        tabelTampil.setSelectionForeground(new java.awt.Color(51, 255, 0));
        jScrollPane1.setViewportView(tabelTampil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void btCariRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariRekapActionPerformed
        cariData();
        hitungTotal();
    }//GEN-LAST:event_btCariRekapActionPerformed

    private void btSegarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSegarkanActionPerformed
        tableCetak();
        txtCari.setText("");
        lbNIP_Lihat.setText("");
        lbNama_Lihat.setText("");
        lbJK.setText("");
        lbT4Lahir_Lihat.setText("");
        lbTglLahir_Lihat.setText("");
        lbPend_Lihat.setText("");
        lbJab_Lihat.setText("");
        lbGol_Lihat.setText("");
        lbDept_Lihat.setText("");
        lbTelp_Lihat.setText("");
        lbAlamat_Lihat.setText("");
        lbTtl_Setahun.setText("");
        tabelTampil.setSelectionMode(0);
        btSegarkan.setEnabled(false);
        btRekap.setEnabled(false);
    }//GEN-LAST:event_btSegarkanActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        cariData();
        hitungTotal();
    }//GEN-LAST:event_txtCariActionPerformed

    private void btRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRekapActionPerformed
        cetakLaporan();
    }//GEN-LAST:event_btRekapActionPerformed

    private void txtCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyTyped
        setInput_Num(evt);
    }//GEN-LAST:event_txtCariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCariRekap;
    private javax.swing.JButton btRekap;
    private javax.swing.JButton btSegarkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbAlamat_Lihat;
    private javax.swing.JLabel lbDept_Lihat;
    private javax.swing.JLabel lbGol_Lihat;
    private javax.swing.JLabel lbJK;
    private javax.swing.JLabel lbJab_Lihat;
    private javax.swing.JLabel lbNIP_Lihat;
    private javax.swing.JLabel lbNama_Lihat;
    private javax.swing.JLabel lbPend_Lihat;
    private javax.swing.JLabel lbT4Lahir_Lihat;
    private javax.swing.JLabel lbTelp_Lihat;
    private javax.swing.JLabel lbTglLahir_Lihat;
    private javax.swing.JLabel lbTtl_Setahun;
    private javax.swing.JTable tabelTampil;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    public Connection konek() throws SQLException, ClassNotFoundException {
        try {
            //
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbabsensi", "root", "root");
            st = conn.createStatement();
            pst = conn.prepareStatement("SET FOREIGN_KEY_CHECKs=0");
            pst.executeQuery();

            return conn;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return null;

    }

    private void tableCetak() {
        try {
            konek();
            Object header[] = {"NIP", "KODE BULAN", "BULAN", "TAHUN", "HADIR", "SAKIT",
                "IZIN", "ALPA", "CUTI", "LEMBUR", "TUGAS LUAR", "TOTAL"};
            DefaultTableModel data = new DefaultTableModel(null, header);
            tabelTampil.setModel(data);

            String query = "SELECT * FROM dbabsensi.`viewrekap`";
            rs = st.executeQuery(query);
            while (rs.next()) {
                String kolom1 = rs.getString("nip");
                String kolom2 = rs.getString("kdBulan");
                String kolom3 = rs.getString("nmBulan");
                String kolom4 = rs.getString("tahun");
                String kolom5 = rs.getString("jHadir");
                String kolom6 = rs.getString("jSakit");
                String kolom7 = rs.getString("jIzin");
                String kolom8 = rs.getString("jTnpKeterangan");
                String kolom9 = rs.getString("jCuti");
                String kolom10 = rs.getString("jLembur");
                String kolom11 = rs.getString("jTugas");
                String kolom12 = rs.getString("ttlsebulan");

                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6,
                    kolom7, kolom8, kolom9, kolom10, kolom11, kolom12};
                data.addRow(kolom);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFrame_Jumlah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inFrame_Jumlah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cariData() {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIP");
        model.addColumn("KODE BULAN");
        model.addColumn("BULAN");
        model.addColumn("TAHUN");
        model.addColumn("HADIR");
        model.addColumn("SAKIT");
        model.addColumn("IZIN");
        model.addColumn("ALPA");
        model.addColumn("CUTI");
        model.addColumn("LEMBUR");
        model.addColumn("TUGAS LUAR");
        model.addColumn("TOTAL");

        try {
            konek();

            if (txtCari.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Anda belum memasukan nip pegawai yang anda ingin cari!", "Informasi", JOptionPane.WARNING_MESSAGE);
            } else {
                String sql = "Select * from viewrekap where nip LIKE'%" + txtCari.getText() + "%'";

                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("nip"),
                        rs.getString("kdBulan"),
                        rs.getString("nmBulan"),
                        rs.getString("tahun"),
                        rs.getString("jHadir"),
                        rs.getString("jSakit"),
                        rs.getString("jIzin"),
                        rs.getString("jTnpKeterangan"),
                        rs.getString("jCuti"),
                        rs.getString("jLembur"),
                        rs.getString("jTugas"),
                        rs.getString("ttlsebulan")
                    });

                    lbNIP_Lihat.setText(" " + rs.getString("nip"));
                    lbNama_Lihat.setText(" " + rs.getString("nama"));
                    lbJK.setText(" " + rs.getString("jk"));
                    lbT4Lahir_Lihat.setText(" " + rs.getString("t4Lahir"));
                    lbTglLahir_Lihat.setText(" " + rs.getString("tglLahir"));
                    lbPend_Lihat.setText(" " + rs.getString("pendidikan"));
                    lbJab_Lihat.setText(" " + rs.getString("jab"));
                    lbGol_Lihat.setText(" " + rs.getString("gol"));
                    lbDept_Lihat.setText(" " + rs.getString("dept"));
                    lbTelp_Lihat.setText(" " + rs.getString("telp"));
                    lbAlamat_Lihat.setText(" " + rs.getString("nmJalan") + " " + rs.getString("noRumah") + ", " + rs.getString("kota"));

                    //dbKoneksi.countAbsent(lbTtl_Setahun);
                    tabelTampil.setModel(model);
                }
                btSegarkan.setEnabled(true);
                btRekap.setEnabled(true);
            }
        } catch (SQLException | ClassNotFoundException | HeadlessException e) {
            e.getStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nip yang anda masukan tidak terdaftar!", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void hitungTotal() {
        try {
            konek();
            String sql = "SELECT SUM(`ttlSebulan`) FROM `dbabsensi`.`tbjumlah` WHERE tbjumlah.`nip` LIKE'%" + txtCari.getText() + "%'";

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lbTtl_Setahun.setText(rs.getString("SUM(`ttlSebulan`)"));
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(inFrame_Rekap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cetakLaporan() {
        try {
            int row = tabelTampil.getSelectedRow();
            TableModel model = tabelTampil.getModel();
            JRTableModelDataSource source = new JRTableModelDataSource(model);
            String reportSource = "src/laporan/inframera.jrxml";

            JasperReport jr = JasperCompileManager.compileReport(reportSource);

            Map<String, Object> params = new HashMap<String, Object>();
            params.put("NIP", "title 2");

            params.put("nip", lbNIP_Lihat.getText());
            params.put("nama", lbNama_Lihat.getText());
            params.put("jk", lbJK.getText());
            params.put("t4Lahir", lbT4Lahir_Lihat.getText());
            params.put("tglLahir", lbTglLahir_Lihat.getText());
            params.put("pendidikan", lbPend_Lihat.getText());
            params.put("jab", lbJab_Lihat.getText());
            params.put("golongan", lbGol_Lihat.getText());
            params.put("dept", lbDept_Lihat.getText());
            params.put("telp", lbTelp_Lihat.getText());
            params.put("alamat", lbAlamat_Lihat.getText());
            params.put("ttlTahunan", lbTtl_Setahun.getText());

            JasperPrint jp = JasperFillManager.fillReport(jr, params, source);
            JasperViewer.viewReport(jp, false);

        } catch (JRException ex) {
            Logger.getLogger(inFrame_Rekap.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
